apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-orchestrator-demo-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-orchestrator-demo
      color: green
  template:
    metadata:
      labels:
        app: k8s-orchestrator-demo
        color: green
    spec:
      containers:
        - name: app
          image: upaio/k8s-orchestrator-demo-python:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "1.5.0"