apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-orchestrator-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-orchestrator-demo
  template:
    metadata:
      labels:
        app: k8s-orchestrator-demo
    spec:
      containers:
        - name: app
          image: upaio/k8s-orchestrator-demo-python:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "1.3.0"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
