apiVersion: v1
kind: Service
metadata:
  name: k8s-orchestrator-demo
spec:
  type: NodePort
  selector:
    app: k8s-orchestrator-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
