name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from properties file
        id: get_version
        run: |
          VERSION=$(grep '^VERSION=' ./app/version.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-orchestrator-demo-python:${{ steps.get_version.outputs.version }}

      - name: (Opcional) Scan image with Trivy
        if: always()
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-orchestrator-demo-python:${{ steps.get_version.outputs.version }}
          format: table
          exit-code: 0
          ignore-unfixed: true
